name: Mike Q
favicon: null
layout_spectrum: 0.74222
typography_spectrum: 0.2858688659034669
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a9602d'
    - '#1b0700'
    - '#f5b763'
    - '#a18c8d'
  brandStrength: 0.6875
  lightness: 0.2070098377298564
  saturation: 0.6670294257346541
  rhythmicContrast: 0.5636008579749614
purpose: []
